variable "prefix" {}
variable "tags" {}
variable "rg_name" {}
variable "rg_location" {}
variable "kubernetes_version" {}
variable "aks_vmss_sku" {}
variable "network_policy" {}
variable "aad_tenant_id" {}
variable "aad_admin_group_id" {}
variable "azurerm_subnet_app_id" {}
variable "azurerm_log_analytics_id" {}
variable "azurerm_subnet_data_id" {}
variable "azurerm_subnet_web_id" {}
#variable "cluster_id" {}
variable "app_node_count" {}
variable "app_max_count" {}
variable "app_min_count" {}
variable "app_max_pods" {}
variable "app_availability_zones" {}
variable "data_node_count" {}
variable "data_max_count" {}
variable "data_min_count" {}
variable "data_max_pods" {}
variable "data_availability_zones" {}
variable "web_node_count" {}
variable "web_max_count" {}
variable "web_min_count" {}
variable "web_max_pods" {}
variable "web_availability_zones" {}
variable "azure_policy" {}