variable "aks_cluster_name" {}
variable "rg_name" {}
variable "rg_id" {}
variable "application_gateway_network_id" {}
variable "environment" {}
variable "acr_name" {}
variable "cluster_id" {}
variable "tags" {}
variable "aks_vmss_sku" {}
variable "azurerm_subnet_data_id" {}
variable "azurerm_subnet_web_id" {}