variable "prefix" {}
variable "tags" {}
variable "rg_name" {}
variable "rg_location" {}
variable "vnet_CIDR" {}
variable "subnet1-CIDR" {}
variable "subnet2-CIDR" {}
variable "subnet3-CIDR" {}
variable "subnet4-CIDR" {}